website/mons/urls.py
"""
	This is the urls module
"""
from django.urls import path
from . import views

app_name = 'mons'
urlpatterns = [
	path('', views.IndexView.as_view(), name='index'),
	path('<int:pk>/', views.DetailView.as_view(), name='detail'),
	path('load', views.load_monsters, name='load')
]

website/summ_auto_website/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('polls/', include('polls.urls')),
	path('monsters/', include('mons.urls')),
	path('admin/', admin.site.urls)
]

website/mons/models.py
"""
	This is the models module
"""
# import datetime

from django.db import models
# from django.utils import timezone

class GoodForTag(models.Model):
	"""
		This is the GoodForTag model
	"""
	tag = models.CharField(
		default='',
		max_length=100,
		unique=False,
		verbose_name='Tag')
	display = models.CharField(
		default='',
		max_length=100,
		unique=False,
		verbose_name='Tag Display')

class Monster(models.Model):
	"""
		This is the Monster model

		* awaken_name
		* element
		* full_name
		* get_from
		* good_for
		* grade
		* grade_num
		* image_sleepy
		* image_awake
		* link_dark
		* link_fire
		* link_light
		* link_water
		* link_wind
		* mon_type
		* rating_keep
		* rating_food
		* rating_best
		* rating_meh
		* score_total
		* score_user
		* skillup_info
		* sleepy_name
		* when_awakened
	"""
	awaken_name = models.CharField(
		default='',
		max_length=50,
		unique=True,
		verbose_name='Awakened Name')
	element = models.CharField(
		choices=[
			('Dark', 'Dark'),
			('Fire', 'Fire'),
			('Light', 'Light'),
			('Water', 'Water'),
			('Wind', 'Wind')
		],
		default='Fire',
		max_length=50,
		verbose_name='Element')
	full_name = models.CharField(
		default='',
		max_length=200,
		unique=True,
		verbose_name='Full Name')
	get_from = models.CharField(
		default='',
		max_length=200,
		verbose_name='Get From')
	good_for = models.ManyToManyField(GoodForTag)
	grade = models.CharField(
		default='',
		max_length=50)
	grade_num = models.SmallIntegerField(
		choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
		default=1,
		verbose_name='Grade Number')
	image_sleepy = models.CharField(
		default='',
		max_length=150,
		verbose_name='Sleepy Image')
	image_awake = models.CharField(
		default='',
		max_length=150,
		verbose_name='Awake Image')
	link_dark = models.CharField(
		default='',
		max_length=100,
		verbose_name='Dark Link')
	link_fire = models.CharField(
		default='',
		max_length=100,
		verbose_name='Fire Link')
	link_light = models.CharField(
		default='',
		max_length=100,
		verbose_name='Light Link')
	link_water = models.CharField(
		default='',
		max_length=100,
		verbose_name='Water Link')
	link_wind = models.CharField(
		default='',
		max_length=100,
		verbose_name='Wind Link')
	mon_type = models.CharField(
		choices=[
			('Attack', 'Attack'),
			('Defense', 'Defense'),
			('HP', 'HP'),
			('Support', 'Support')
		],
		default='Support',
		max_length=25,
		verbose_name='Monster Type')
	rating_keep = models.FloatField(
		default=0,
		verbose_name='Rating: Keep')
	rating_food = models.FloatField(
		default=0,
		verbose_name='Rating: Food')
	rating_best = models.FloatField(
		default=0,
		verbose_name='Rating: The Best')
	rating_meh = models.FloatField(
		default=0,
		verbose_name='Rating: Meh')
	score_total = models.FloatField(
		default=0,
		verbose_name='Total Score')
	score_user = models.FloatField(
		default=0,
		verbose_name='User Score')
	skillup_info = models.CharField(
		default='',
		max_length=200,
		verbose_name='Skillup Information')
	sleepy_name = models.CharField(
		default='',
		max_length=50,
		verbose_name='Sleepy Name')
	when_awakened = models.CharField(
		default='',
		max_length=200,
		verbose_name='When Awakened')
	# pub_date = models.DateTimeField('date published')

	def __str__(self):# pragma: no cover
		"""
			This method provides a useful string representation
			of this model
		"""
		return f'[{self.full_name} | {self.element}]'

	# is_recent_publication.admin_order_field = 'pub_date'
	# is_recent_publication.boolean = True
	# is_recent_publication.short_description = 'Published recently?'

website/mons/views.py
"""
	This is the views module
"""
import json
import os
# from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
# from django.utils import timezone
from django.views import generic
from .models import GoodForTag, Monster

TEMPLATE_DIR = 'mons'

class IndexView(generic.ListView):# pylint: disable=R0901
	"""
		This generic view is the index for the mons app
	"""
	template_name = f'{TEMPLATE_DIR}/index.html'
	context_object_name = 'monster_list'

	def get_queryset(self):
		"""
			Return all mons ordered by their awakened name
		"""
		return Monster.objects.all().order_by('awaken_name')

class DetailView(generic.DetailView):# pylint: disable=R0901
	"""
		This generic view is the detail for a specific Monster
	"""
	model = Monster
	template_name = f'{TEMPLATE_DIR}/detail.html'

def load_from_disk(filepath):
	"""
		This method attempts to load a JSON file from
		the disk, given a `filepath`
		* filepath
	"""
	data = {}
	with open(filepath, 'r') as in_file:
		data = json.load(in_file)
	return data

def create_monster(json_data):
	"""
		Create a monster with the given JSON
		* json
	"""
	print(f'about to parse the good fors...')
	good_fors = []
	for tmp in json_data['good_for']:
		good_fors.append(GoodForTag.objects.create(
			display=tmp,
			tag=tmp
		))
	print(f'parsed the good fors...')

	# print(f'create_monster got this JSON={json_data}')
	new_mon =  Monster.objects.create(
		awaken_name=json_data['name_awaken'],
		element=json_data['element'].capitalize(),
		full_name=json_data['name_full'],
		get_from=json_data['get_from'],
		good_for=[],
		grade=json_data['grade'],
		grade_num=json_data['grade_num'],
		image_sleepy=json_data['links']['IMAGE_SLEEPY'],
		image_awake=json_data['links']['IMAGE_AWAKE'],
		link_dark=json_data['links']['DARK'],
		link_fire=json_data['links']['FIRE'],
		link_light=json_data['links']['LIGHT'],
		link_water=json_data['links']['WATER'],
		link_wind=json_data['links']['WIND'],
		mon_type=json_data['mon_type'],
		rating_keep=json_data['ratings']['KEEP_IT'],
		rating_food=json_data['ratings']['FOOD'],
		rating_best=json_data['ratings']['THE_BEST'],
		rating_meh=json_data['ratings']['MEH'],
		score_total=json_data['score_total'],
		score_user=json_data['score_user'],
		skillup_info=json_data['skillup_info'],
		sleepy_name=json_data['name_sleepy'],
		when_awakened=json_data['when_awaken'])
	print(f'about to set the good fors...')
	new_mon.good_for.set(good_fors)
	print(f'returning...')
	return new_mon

def load_monsters(request):
	"""
		This view is for providing control via the website
		to load monsters from the parsed JSON files
	"""
	if request.method.lower() == 'get':
		return render(request, template_name=f'{TEMPLATE_DIR}/load.html', status=200)

	curr_dir = os.path.dirname(os.path.abspath(__file__))
	website_dir = os.path.dirname(curr_dir)
	summ_auto_repo_dir = os.path.dirname(website_dir)
	mon_data_dir = os.path.join(summ_auto_repo_dir, 'data', 'mons')

	for filepath in os.listdir(mon_data_dir):
		full_path = os.path.join(mon_data_dir, filepath)
		json_mon = load_from_disk(full_path)
		awaken_name = json_mon['name_awaken']
		# print(f'Looking up with awaken_name={awaken_name}')

		try:
			# NOTE: we use awaken name because it is unique
			print(f'About to get old_mon...')
			old_mon = Monster.objects.get(awaken_name=awaken_name)
			print(f'Monster is old={filepath}')
			good_fors = []
			for good_for in json_mon['good_for']:
				good_fors.append(GoodForTag.objects.create(
					display=good_for,
					tag=good_for
				))

			old_mon.awaken_name = json_mon['name_awaken']
			old_mon.element = json_mon['element'].capitalize()
			old_mon.full_name = json_mon['name_full']
			old_mon.get_from = json_mon['get_from']
			old_mon.good_for.set(good_fors)
			old_mon.grade = json_mon['grade']
			old_mon.grade_num = json_mon['grade_num']
			old_mon.image_sleepy = json_mon['links']['IMAGE_SLEEPY']
			old_mon.image_awake = json_mon['links']['IMAGE_AWAKE']
			old_mon.link_dark = json_mon['links']['DARK']
			old_mon.link_fire = json_mon['links']['FIRE']
			old_mon.link_light = json_mon['links']['LIGHT']
			old_mon.link_water = json_mon['links']['WATER']
			old_mon.link_wind = json_mon['links']['WIND']
			old_mon.mon_type = json_mon['mon_type']
			old_mon.rating_keep = json_mon['ratings']['KEEP_IT']
			old_mon.rating_food = json_mon['ratings']['FOOD']
			old_mon.rating_best = json_mon['ratings']['THE_BEST']
			old_mon.rating_meh = json_mon['ratings']['MEH']
			old_mon.score_total = json_mon['score_total']
			old_mon.score_user = json_mon['score_user']
			old_mon.skillup_info = json_mon['skillup_info']
			old_mon.sleepy_name = json_mon['name_sleepy']
			old_mon.when_awakened = json_mon['when_awaken']
		except Monster.DoesNotExist:
			print(f'Monster is new={filepath}')
			old_mon = create_monster(json_mon)
		print(f'Attempting to save {awaken_name} with {vars(old_mon)}')
		old_mon.save()

	return HttpResponseRedirect(reverse('mons:index'))

website/mons/templates/mons/base.html
{% load static %}
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'mons/style.css' %}" />
    </head>
    <body>
        <nav>
            <a href="/monsters/">Monster List</a>
            <a href="/monsters/load">Load From JSON</a>
        </nav>
        <section class="content">
            {% block content %}
            {% endblock %}
        </section>
    </body>
</html>

website/mons/templates/mons/detail.html
{% extends 'mons/base.html' %}
{% block title %}{{ monster.full_name }}{% endblock %}

{% block content %}
    <h1>{{ monster.full_name }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <div class="monster-detail {{ monster.element|lower }}">
        <table>
            <thead>
                <tr>
                    <th>Stat</th>
                    <th>Detail</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Awakened Name</td>
                    <td>{{ monster.awaken_name }}</td>
                </tr>
                <tr>
                    <td>Element</td>
                    <td>{{ monster.element }}</td>
                </tr>
                <tr>
                    <td>Get From</td>
                    <td>{{ monster.get_from }}</td>
                </tr>
                <tr>
                    <td>Good For</td>
                    <td>{{ monster.good_for }}</td>
                </tr>
                <tr>
                    <td>Grade</td>
                    <td>{{ monster.grade }}</td>
                </tr>
                <tr>
                    <td>Grade Number</td>
                    <td>{{ monster.grade_num }}</td>
                </tr>
                <tr>
                    <td>Images</td>
                    <td>
                        <div class="img-container">
                            <p>Sleepy</p>
                            <a href="{{monster.image_sleepy }}" target="_blank">
                                <img src="{{ monster.image_sleepy }}" alt="{{ monster.sleepy_name }} Sleepy Image" class="monster-img" />
                            </a>
                        </div>
                        <div class="img-container">
                            <p>Awake</p>
                            <a href="{{monster.image_awake }}" target="_blank">
                                <img src="{{ monster.image_awake }}" alt="{{ monster.awaken_name }} Awakened Image" class="monster-img" />
                            </a>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>Links</td>
                    <td>
                        <table>
                            <thead>
                                <tr>
                                    <th>Link Type</th>
                                    <th>Link</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Dark Link</td>
                                    <td><a href="{{ monster.link_dark }}" target="_blank">{{ monster.link_dark }}</a></td>
                                </tr>
                                <tr>
                                    <td>Fire Link</td>
                                    <td><a href="{{ monster.link_fire }}" target="_blank">{{ monster.link_fire }}</a></td>
                                </tr>
                                <tr>
                                    <td>Light Link</td>
                                    <td><a href="{{ monster.link_light }}" target="_blank">{{ monster.link_light }}</a></td>
                                </tr>
                                <tr>
                                    <td>Water Link</td>
                                    <td><a href="{{ monster.link_water }}" target="_blank">{{ monster.link_water }}</a></td>
                                </tr>
                                <tr>
                                    <td>Wind Link</td>
                                    <td><a href="{{ monster.link_wind }}" target="_blank">{{ monster.link_wind }}</a></td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td>Monster Type</td>
                    <td>{{ monster.mon_type }}</td>
                </tr>
                <tr>
                    <td>Ratings</td>
                    <td>
                        <table>
                            <thead>
                                <tr>
                                    <th>Rating Type</th>
                                    <th>Rating</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Keep It</td>
                                    <td>{{ monster.rating_keep }}</td>
                                </tr>
                                <tr>
                                    <td>Food</td>
                                    <td>{{ monster.rating_food }}</td>
                                </tr>
                                <tr>
                                    <td>The Best</td>
                                    <td>{{ monster.rating_best }}</td>
                                </tr>
                                <tr>
                                    <td>Meh</td>
                                    <td>{{ monster.rating_meh }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td>Score Total</td>
                    <td>{{ monster.score_total }}</td>
                </tr>
                <tr>
                    <td>Score User</td>
                    <td>{{ monster.score_user }}</td>
                </tr>
                <tr>
                    <td>Skillup Info</td>
                    <td>{{ monster.skillup_info }}</td>
                </tr>
                <tr>
                    <td>Sleepy Name</td>
                    <td>{{ monster.sleepy_name }}</td>
                </tr>
                <tr>
                    <td>When Awakened</td>
                    <td>{{ monster.when_awakened }}</td>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

website/mons/templates/mons/index.html
{% extends 'mons/base.html' %}
{% block title %}Monster List{% endblock %}

{% block content %}
    <h1>Monster List</h1>

    {% if monster_list %}
        <ul>
        {% for monster in monster_list %}
        <li class="monster-list-item {{ monster.element|lower }}">
            <a href="{% url 'mons:detail' monster.id %}">
                <span>
                    {{ monster.awaken_name }}
                </span>
                <div class="monster-list-image-container">
                    <img src="{{ monster.image_sleepy }}" alt="{{ monster.sleepy_name }} Sleepy Image" class="monster-img img-mini" />
                </div>
                <div class="monster-list-image-container">
                    <img src="{{ monster.image_awake }}" alt="{{ monster.awaken_name }} Awakened Image" class="monster-img img-mini" />
                </div>
                
            </a>
        </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No monsters are available</p>
    {% endif %}
{% endblock %}

website/mons/templates/mons/load.html
{% extends 'mons/base.html' %}
{% block title %}Load Monster From JSON{% endblock %}

{% block content %}
    <h1>Click or tap the button below to load monsters from parsed JSON files in the repository</h1>

    <form action="{% url 'mons:load' %}" method="post" class="load-form">
        {% csrf_token %}
        <input type="submit" value="Load JSON" />
    </form>
{% endblock %}